version: '2'
services:
  couchpotato:
    image: linuxserver/couchpotato
    hostname: couchpotato
    environment:
      PGID: '1013'
      PUID: '1013'
      TZ: America/Chicago
    stdin_open: true
    volumes:
    - /mnt/docker/couchpotato:/config
    - /mnt/media:/mnt/media
    dns:
    - 10.1.1.1
    domainname: mccorkle.co
    tty: true
    ports:
    - 5050:5050/tcp
    labels:
      io.rancher.container.pull_image: always
