version: '2'
services:
  homeassistant:
    image: homeassistant/home-assistant
    hostname: homeassistant
    environment:
      TZ: America/Chicago
    stdin_open: true
    volumes:
    - /mnt/docker/homeassistant:/config
    dns:
    - 10.1.1.1
    domainname: mccorkle.co
    tty: true
    ports:
    - 8123:8123/tcp
    labels:
      io.rancher.container.pull_image: always
