version: '2'
services:
  plex:
    scale: 1
    start_on_create: true
  sabnzbd:
    scale: 1
    start_on_create: true
  sonarr:
    scale: 1
    start_on_create: true
  couchpotato:
    scale: 1
    start_on_create: true
