version: '3'

services:
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    # ports:
    #   - $SABNZBD_PORT:8080
    volumes:
      - /mnt/docker/sabnzbd:/config
      - /mnt/media:/mnt/media
    environment:
      PUID: '1013'
      PGID: '1013'
      TZ: $TZ
    stdin_open: true
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.sabnzbd-rtr.entrypoints=https
    #   - traefik.http.routers.sabnzbd-rtr.rule=Host(`sabnzbd.$DOMAINNAME`)
    #   - traefik.http.routers.sabnzbd-rtr.tls=true
    #   - traefik.http.routers.sabnzbd-rtr.middlewares=chain-authelia@file
    #   - traefik.http.services.sabnzbd-svc.loadbalancer.server.port=8080
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.sabnzbd-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.sabnzbd-rtr-bypass.rule=Host(`sabnzbd.$DOMAINNAME`) && Query(`apikey`, `$SABNZBD_API_KEY`)"
      - traefik.http.routers.sabnzbd-rtr-bypass.tls=true
      - "traefik.http.routers.sabnzbd-rtr-bypass.priority=100"
      ## HTTP Routers Auth
      - "traefik.http.routers.sabnzbd-rtr.entrypoints=https"
      - "traefik.http.routers.sabnzbd-rtr.rule=Host(`sabnzbd.$DOMAINNAME`)"
      - traefik.http.routers.sabnzbd-rtr.tls=true
      - "traefik.http.routers.sabnzbd-rtr.priority=99"
      # Middlewares
      - "traefik.http.routers.sabnzbd-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.sabnzbd-rtr.middlewares=chain-authelia@file"
      # HTTP Services
      - "traefik.http.routers.sabnzbd-rtr.service=sabnzbd-svc"
      - "traefik.http.routers.sabnzbd-rtr-bypass.service=sabnzbd-svc"
      - "traefik.http.services.sabnzbd-svc.loadbalancer.server.port=8080"
networks:
  t2_proxy:
    external: true
