version: '2'
services:
  sabnzbd:
    image: linuxserver/sabnzbd
    restart: unless-stopped
    hostname: sabnzbd
    environment:
      PGID: '1013'
      PUID: '1013'
      TZ: America/Chicago
    stdin_open: true
    volumes:
    - /mnt/docker/sabnzbd:/config
    - /mnt/media:/mnt/media
    dns:
    - 10.1.1.1
    domainname: mccorkle.co
    tty: true
    ports:
    - 8181:8080/tcp
    - 9191:9090/tcp
    labels:
      io.rancher.container.pull_image: always
