## Dynamic configuration
[http.services]
  [http.services.heatermeter-svc.loadBalancer]
    [[http.services.heatermeter-svc.loadBalancer.servers]]
      url = "http://10.1.1.60/"
  [http.services.homeassistant-svc.loadBalancer]
    [[http.services.homeassistant-svc.loadBalancer.servers]]
      url = "http://10.1.1.62:8123/"